#!/usr/bin/env python3
# -*- coding: UTF-8

"""
Dewyatochka \^-^/ !!!
"""

__author__ = 'Kawashiro Nitori'

import sys
from dewyatochka.daemon import Application

if __name__ == '__main__':
    Application().run(sys.argv)
