#!/usr/bin/env python3
# -*- coding: UTF-8

""" Dewyatochka daemon script

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Copyright (C) 2015 Kawashiro Nitori

Usage
=====
    dewyatochkad [-h] [--config CONFIG] [--nodaemon]

Optional arguments
==================
    -h, --help       Show this help message and exit
    --config CONFIG  Path to config file to use
    --nodaemon       Do not detach process from console
"""

import sys

from dewyatochka.applications import daemon

if __name__ == '__main__':
    # Run, Dewyatochka, run! ^-^
    daemon.Application().run(sys.argv)
